apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-master-volume-0
  labels:
    type: local
    app: spark-master
spec:
  storageClassName: manual
  claimRef:
    name: spark-master-volume-claim-0
    namespace: rebios-spark
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/spark/master/apps
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-master-volume-1
  labels:
    type: local
    app: spark-master
spec:
  storageClassName: manual
  claimRef: 
    name: spark-master-volume-claim-1
    namespace: rebios-spark
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/spark/master/data
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-master-volume-2
  labels:
    type: local
    app: spark-master
spec:
  storageClassName: manual
  claimRef:
    name: spark-master-volume-claim-2
    namespace: rebios-spark
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/spark/master/logs
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-master-volume-3
  labels:
    type: local
    app: spark-master
spec:
  storageClassName: manual
  claimRef:
    name: spark-master-volume-claim-3
    namespace: rebios-spark
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/spark/master/spark-events
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-master-volume-4
  labels:
    type: local
    app: spark-master
spec:
  storageClassName: manual
  claimRef:
    name: spark-master-volume-claim-4
    namespace: rebios-spark
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/spark/etl-rebios
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-master-volume-5
  labels:
    type: local
    app: spark-master
spec:
  storageClassName: manual
  claimRef:
    name: spark-master-volume-claim-5
    namespace: rebios-spark
  capacity:
    storage: 1.5Gi
    accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/spark/scripts

      

